### ISSUE TITLE
Ufunc 'isnan' not supported for the input types

### ISSUE THREAD

**Issue by Lukerko** [loneharoon/GSP_energy_disaggregator#4]
Hi,

I have a problem with compiling using Python 3.7 on PyCharm 2018.3.4 x64.
Compiling stop at step 3 of 6> generates full power series of appliances and display following error:
`File "C:/Users/hacke/PycharmProjects/GSP_Disagregator/gsp_disaggregator.py", line 72, in <module>
    power_series, appliance_signatures = gsp.generate_appliance_powerseries(appliance_pairs, delta_p)
  File "C:\Users\hacke\PycharmProjects\GSP_Disagregator\gsp_support.py", line 194, in generate_appliance_powerseries
    powerval = interpolate_values(final) if sum(np.isnan(final)) else final
TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''`

Thanks for response

**Comment by professor-who** [comment]
Hi! I meet the same problem, have you ever solved it?

**Comment by Lukerko** [comment]
Hi, yes.
You must run this code on Python version 2.7

**Comment by professor-who** [comment]
Thank you very much, i will try this way now.



------------------ 原始邮件 ------------------
发件人: "Lukerko"<notifications@github.com>;
发送时间: 2019年5月23日(星期四) 下午2:51
收件人: "loneharoon/GSP_energy_disaggregator"<GSP_energy_disaggregator@noreply.github.com>;
抄送: "bestfgq"<512735525@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [loneharoon/GSP_energy_disaggregator] Ufunc 'isnan' not supportedfor the input types (#4)




Hi, yes.
 You must run this code on Python version 2.7
